<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('city')->truncate();

        $city = array(
            array('id' => '1','name' => 'Ciudad','department' => 'Departamento','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '2','name' => 'Puerto Casado','department' => 'Alto Paraguay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '3','name' => 'Capitán Carmelo Peralta','department' => 'Alto Paraguay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '4','name' => 'Fuerte Olimpo','department' => 'Alto Paraguay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '5','name' => 'Bahía Negra','department' => 'Alto Paraguay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '6','name' => 'Ciudad del Este','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '7','name' => 'Presidente Franco','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '8','name' => 'Minga Guazú','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '9','name' => 'Hernandarias','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '10','name' => 'Itakyry','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '11','name' => 'Santa Rita','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '12','name' => 'Juan Emiliano O\'Leary','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '13','name' => 'Doctor Juan León Mallorquín','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '14','name' => 'Minga Porá','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '15','name' => 'San Alberto','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '16','name' => 'Yguazú','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '17','name' => 'San Cristóbal','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '18','name' => 'Los Cedrales','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '19','name' => 'Doctor Raúl Peña','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '20','name' => 'Ñacunday','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '21','name' => 'Mbaracayú','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '22','name' => 'Tavapy','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '23','name' => 'Santa Rosa del Monday','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '24','name' => 'Iruña','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '25','name' => 'Naranjal','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '26','name' => 'Domingo Martínez de Irala','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '27','name' => 'Santa Fe del Paraná','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '28','name' => 'Pedro Juan Caballero','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '29','name' => 'Capitán Bado','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '30','name' => 'Bella Vista Norte','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '31','name' => 'Zanja Pytá','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '32','name' => 'Karapaí','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '33','name' => 'Cerro Corá','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '34','name' => 'Mariscal José Félix Estigarribia','department' => 'Boquerón','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '35','name' => 'Filadelfia','department' => 'Boquerón','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '36','name' => 'Loma Plata','department' => 'Boquerón','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '37','name' => 'Boquerón','department' => 'Boquerón','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '38','name' => 'Caaguazú','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '39','name' => 'Coronel Oviedo','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '40','name' => 'Doctor Juan Eulogio Estigarribia','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '41','name' => 'Yhú','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '42','name' => 'Repatriación','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '43','name' => 'Doctor Juan Manuel Frutos','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '44','name' => 'San José de los Arroyos','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '45','name' => 'San Joaquín','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '46','name' => 'Raúl Arsenio Oviedo','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '47','name' => 'Carayaó','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '48','name' => 'Tembiaporá','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '49','name' => 'Santa Rosa del Mbutuy','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '50','name' => 'Vaquería','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '51','name' => 'José Domingo Ocampos','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '52','name' => 'Tres de Febrero','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '53','name' => 'Regimiento de Infantería Tres Corrales','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '54','name' => 'Doctor Cecilio Báez','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '55','name' => 'Mariscal Francisco Solano López','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '56','name' => 'Simón Bolívar','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '57','name' => 'La Pastora','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '58','name' => 'Nueva Toledo','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '59','name' => 'Nueva Londres','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '60','name' => 'San Juan Nepomuceno','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '61','name' => 'Abaí','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '62','name' => 'Caazapá','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '63','name' => 'Yuty','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '64','name' => 'Tres de Mayo','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '65','name' => 'Tavaí','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '66','name' => 'Fulgencio Yegros','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '67','name' => 'General Higinio Morínigo','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '68','name' => 'Buena Vista','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '69','name' => 'Doctor Moisés Santiago Bertoni','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '70','name' => 'Maciel','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '71','name' => 'Curuguaty','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '72','name' => 'Salto del Guairá','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '73','name' => 'Yasy Cañy','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '74','name' => 'Villa Ygatimí','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '75','name' => 'Ybyrarobaná','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '76','name' => 'Nueva Esperanza','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '77','name' => 'General Francisco Caballero Álvarez','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '78','name' => 'Yby Pytá','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '79','name' => 'Corpus Christi','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '80','name' => 'La Paloma del Espíritu Santo','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '81','name' => 'Ypejhú','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '82','name' => 'Katueté','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '83','name' => 'Itanará','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '84','name' => 'Maracaná','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '85','name' => 'Laurel','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '86','name' => 'Luque','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '87','name' => 'San Lorenzo','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '88','name' => 'Capiatá','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '89','name' => 'Lambaré','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '90','name' => 'Fernando de la Mora','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '91','name' => 'Limpio','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '92','name' => 'Ñemby','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '93','name' => 'Itauguá','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '94','name' => 'Mariano Roque Alonso','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '95','name' => 'Itá','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '96','name' => 'Villa Elisa','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '97','name' => 'Areguá','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '98','name' => 'San Antonio','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '99','name' => 'Ypané','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '100','name' => 'Julián Augusto Saldívar','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '101','name' => 'Villeta','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '102','name' => 'Guarambaré','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '103','name' => 'Ypacaraí','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '104','name' => 'Nueva Italia','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '105','name' => 'Concepción','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '106','name' => 'Horqueta','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '107','name' => 'Yby Yaú','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '108','name' => 'Loreto','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '109','name' => 'Belén','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '110','name' => 'San Lázaro','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '111','name' => 'Azotey','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '112','name' => 'Sargento José Félix López','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '113','name' => 'San Alfredo','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '114','name' => 'Paso Barreto','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '115','name' => 'San Carlos del Apa','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '116','name' => 'Arroyito','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '117','name' => 'Paso Horqueta','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '118','name' => 'Paso Barreto','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '119','name' => 'Caacupé','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '120','name' => 'Tobatí','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '121','name' => 'Piribebuy','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '122','name' => 'Arroyos y Esteros','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '123','name' => 'Eusebio Ayala','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '124','name' => 'Emboscada','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '125','name' => 'Atyrá','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '126','name' => 'Altos','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '127','name' => 'Caraguatay','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '128','name' => 'San Bernardino','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '129','name' => 'Itacurubí de la Cordillera','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '130','name' => 'Isla Pucú','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '131','name' => 'Valenzuela','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '132','name' => 'Juan de Mena','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '133','name' => 'Primero de Marzo','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '134','name' => 'Santa Elena','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '135','name' => 'San José Obrero','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '136','name' => 'Mbocayaty del Yhaguy','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '137','name' => 'Nueva Colombia','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '138','name' => 'Loma Grande','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '139','name' => 'Asunción','department' => 'Capital','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '140','name' => 'Villarrica','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '141','name' => 'Independencia','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '142','name' => 'Paso Yobái','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '143','name' => 'Capitán Mauricio José Troche','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '144','name' => 'Borja','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '145','name' => 'Mbocayaty del Guairá','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '146','name' => 'Iturbe','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '147','name' => 'General Eugenio Alejandrino Garay','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '148','name' => 'Itapé','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '149','name' => 'Coronel Martínez','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '150','name' => 'José A. Fassardi','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '151','name' => 'Félix Pérez Cardozo','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '152','name' => 'Natalicio Talavera','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '153','name' => 'Yataity del Guairá','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '154','name' => 'Ñumí','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '155','name' => 'Tebicuary','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '156','name' => 'San Salvador','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '157','name' => 'Doctor Bottrell','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '158','name' => 'Encarnación','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '159','name' => 'Cambyretá','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '160','name' => 'San Pedro del Paraná','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '161','name' => 'Tomás Romero Pereira','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '162','name' => 'Edelira','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '163','name' => 'San Rafael del Paraná','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '164','name' => 'Coronel José Félix Bogado','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '165','name' => 'Natalio','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '166','name' => 'Carlos Antonio López','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '167','name' => 'Alto Verá','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '168','name' => 'Obligado','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '169','name' => 'Itapúa Poty','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '170','name' => 'Hohenau','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '171','name' => 'Mayor Otaño','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '172','name' => 'Bella Vista','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '173','name' => 'Capitán Meza','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '174','name' => 'Capitán Miranda','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '175','name' => 'Yatytay','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '176','name' => 'General Artigas','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '177','name' => 'Fram','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '178','name' => 'San Cosme y Damián','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '179','name' => 'Trinidad','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '180','name' => 'San Juan del Paraná','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '181','name' => 'Pirapó','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '182','name' => 'Carmen del Paraná','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '183','name' => 'General Delgado','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '184','name' => 'Nueva Alborada','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '185','name' => 'Jesús','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '186','name' => 'José Leandro Oviedo','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '187','name' => 'La Paz','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '188','name' => 'San Ignacio Guazú','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '189','name' => 'San Juan Bautista','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '190','name' => 'Ayolas','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '191','name' => 'Santa Rosa de Lima','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '192','name' => 'Santa María de Fe','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '193','name' => 'Santiago','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '194','name' => 'San Miguel','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '195','name' => 'Villa Florida','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '196','name' => 'San Patricio','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '197','name' => 'Yabebyry','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '198','name' => 'Pilar','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '199','name' => 'Alberdi','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '200','name' => 'San Juan Bautista del Ñeembucú','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '201','name' => 'Cerrito','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '202','name' => 'Mayor José Martínez','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '203','name' => 'General José Eduvigis Díaz','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '204','name' => 'Tacuaras','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '205','name' => 'Villa Oliva','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '206','name' => 'Laureles','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '207','name' => 'Humaitá','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '208','name' => 'Isla Umbú','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '209','name' => 'Villalbín','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '210','name' => 'Guazú Cuá','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '211','name' => 'Paso de Patria','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '212','name' => 'Desmochados','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '213','name' => 'Villa Franca','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '214','name' => 'Carapeguá','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '215','name' => 'Yaguarón','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '216','name' => 'Ybycuí','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '217','name' => 'Paraguarí','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '218','name' => 'Quiindy','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '219','name' => 'Pirayú','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '220','name' => 'Acahay','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '221','name' => 'Mbuyapey','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '222','name' => 'San Roque González de Santa Cruz','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '223','name' => 'Escobar','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '224','name' => 'Caapucú','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '225','name' => 'Quyquyhó','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '226','name' => 'Ybytymí','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '227','name' => 'General Bernardino Caballero','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '228','name' => 'Sapucai','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '229','name' => 'La Colmena','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '230','name' => 'Tebicuarymí','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '231','name' => 'María Antonia','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '232','name' => 'Villa Hayes','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '233','name' => 'Teniente Primero Manuel Irala Fernández','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '234','name' => 'Benjamín Aceval','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '235','name' => 'Puerto Pinasco','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '236','name' => 'Nanawa','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '237','name' => 'José Falcón','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '238','name' => 'Teniente Esteban Martínez','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '239','name' => 'General José María Bruguez','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '240','name' => 'Nueva Asunción','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '241','name' => 'Campo Aceval','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '242','name' => 'San Estanislao','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '243','name' => 'Capiibary','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '244','name' => 'Santa Rosa del Aguaray','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '245','name' => 'San Pedro de Ycuamandiyú','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '246','name' => 'Guayaibí','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '247','name' => 'Choré','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '248','name' => 'Liberación','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '249','name' => 'General Isidoro Resquín','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '250','name' => 'General Elizardo Aquino','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '251','name' => 'Yrybucuá','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '252','name' => 'Tacuatí','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '253','name' => 'Yataity del Norte','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '254','name' => 'Lima','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '255','name' => 'Itacurubí del Rosario','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '256','name' => 'Villa del Rosario','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '257','name' => '25 de Diciembre','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '258','name' => 'Nueva Germania','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '259','name' => 'Unión','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '260','name' => 'Antequera','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '261','name' => 'San Pablo','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '262','name' => 'San Vicente Pancholo','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '263','name' => 'San José del Rosario','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '264','name' => 'Ciudad','department' => 'Departamento','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '265','name' => 'Puerto Casado','department' => 'Alto Paraguay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '266','name' => 'Capitán Carmelo Peralta','department' => 'Alto Paraguay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '267','name' => 'Fuerte Olimpo','department' => 'Alto Paraguay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '268','name' => 'Bahía Negra','department' => 'Alto Paraguay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '269','name' => 'Ciudad del Este','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '270','name' => 'Presidente Franco','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '271','name' => 'Minga Guazú','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '272','name' => 'Hernandarias','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '273','name' => 'Itakyry','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '274','name' => 'Santa Rita','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '275','name' => 'Juan Emiliano O\'Leary','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '276','name' => 'Doctor Juan León Mallorquín','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '277','name' => 'Minga Porá','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '278','name' => 'San Alberto','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '279','name' => 'Yguazú','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '280','name' => 'San Cristóbal','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '281','name' => 'Los Cedrales','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '282','name' => 'Doctor Raúl Peña','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '283','name' => 'Ñacunday','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '284','name' => 'Mbaracayú','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '285','name' => 'Tavapy','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '286','name' => 'Santa Rosa del Monday','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '287','name' => 'Iruña','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '288','name' => 'Naranjal','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '289','name' => 'Domingo Martínez de Irala','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '290','name' => 'Santa Fe del Paraná','department' => 'Alto Paraná','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '291','name' => 'Pedro Juan Caballero','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '292','name' => 'Capitán Bado','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '293','name' => 'Bella Vista Norte','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '294','name' => 'Zanja Pytá','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '295','name' => 'Karapaí','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '296','name' => 'Cerro Corá','department' => 'Amambay','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '297','name' => 'Mariscal José Félix Estigarribia','department' => 'Boquerón','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '298','name' => 'Filadelfia','department' => 'Boquerón','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '299','name' => 'Loma Plata','department' => 'Boquerón','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '300','name' => 'Boquerón','department' => 'Boquerón','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '301','name' => 'Caaguazú','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '302','name' => 'Coronel Oviedo','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '303','name' => 'Doctor Juan Eulogio Estigarribia','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '304','name' => 'Yhú','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '305','name' => 'Repatriación','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '306','name' => 'Doctor Juan Manuel Frutos','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '307','name' => 'San José de los Arroyos','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '308','name' => 'San Joaquín','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '309','name' => 'Raúl Arsenio Oviedo','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '310','name' => 'Carayaó','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '311','name' => 'Tembiaporá','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '312','name' => 'Santa Rosa del Mbutuy','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '313','name' => 'Vaquería','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '314','name' => 'José Domingo Ocampos','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '315','name' => 'Tres de Febrero','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '316','name' => 'Regimiento de Infantería Tres Corrales','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '317','name' => 'Doctor Cecilio Báez','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '318','name' => 'Mariscal Francisco Solano López','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '319','name' => 'Simón Bolívar','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '320','name' => 'La Pastora','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '321','name' => 'Nueva Toledo','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '322','name' => 'Nueva Londres','department' => 'Caaguazú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '323','name' => 'San Juan Nepomuceno','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '324','name' => 'Abaí','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '325','name' => 'Caazapá','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '326','name' => 'Yuty','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '327','name' => 'Tres de Mayo','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '328','name' => 'Tavaí','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '329','name' => 'Fulgencio Yegros','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '330','name' => 'General Higinio Morínigo','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '331','name' => 'Buena Vista','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '332','name' => 'Doctor Moisés Santiago Bertoni','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '333','name' => 'Maciel','department' => 'Caazapá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '334','name' => 'Curuguaty','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '335','name' => 'Salto del Guairá','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '336','name' => 'Yasy Cañy','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '337','name' => 'Villa Ygatimí','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '338','name' => 'Ybyrarobaná','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '339','name' => 'Nueva Esperanza','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '340','name' => 'General Francisco Caballero Álvarez','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '341','name' => 'Yby Pytá','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '342','name' => 'Corpus Christi','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '343','name' => 'La Paloma del Espíritu Santo','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '344','name' => 'Ypejhú','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '345','name' => 'Katueté','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '346','name' => 'Itanará','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '347','name' => 'Maracaná','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '348','name' => 'Laurel','department' => 'Canindeyú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '349','name' => 'Luque','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '350','name' => 'San Lorenzo','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '351','name' => 'Capiatá','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '352','name' => 'Lambaré','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '353','name' => 'Fernando de la Mora','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '354','name' => 'Limpio','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '355','name' => 'Ñemby','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '356','name' => 'Itauguá','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '357','name' => 'Mariano Roque Alonso','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '358','name' => 'Itá','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '359','name' => 'Villa Elisa','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '360','name' => 'Areguá','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '361','name' => 'San Antonio','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '362','name' => 'Ypané','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '363','name' => 'Julián Augusto Saldívar','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '364','name' => 'Villeta','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '365','name' => 'Guarambaré','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '366','name' => 'Ypacaraí','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '367','name' => 'Nueva Italia','department' => 'Central','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '368','name' => 'Concepción','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '369','name' => 'Horqueta','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '370','name' => 'Yby Yaú','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '371','name' => 'Loreto','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '372','name' => 'Belén','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '373','name' => 'San Lázaro','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '374','name' => 'Azotey','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '375','name' => 'Sargento José Félix López','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '376','name' => 'San Alfredo','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '377','name' => 'Paso Barreto','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '378','name' => 'San Carlos del Apa','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '379','name' => 'Arroyito','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '380','name' => 'Paso Horqueta','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '381','name' => 'Paso Barreto','department' => 'Concepción','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '382','name' => 'Caacupé','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '383','name' => 'Tobatí','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '384','name' => 'Piribebuy','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '385','name' => 'Arroyos y Esteros','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '386','name' => 'Eusebio Ayala','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '387','name' => 'Emboscada','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '388','name' => 'Atyrá','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '389','name' => 'Altos','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '390','name' => 'Caraguatay','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '391','name' => 'San Bernardino','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '392','name' => 'Itacurubí de la Cordillera','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '393','name' => 'Isla Pucú','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '394','name' => 'Valenzuela','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '395','name' => 'Juan de Mena','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '396','name' => 'Primero de Marzo','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '397','name' => 'Santa Elena','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '398','name' => 'San José Obrero','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '399','name' => 'Mbocayaty del Yhaguy','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '400','name' => 'Nueva Colombia','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '401','name' => 'Loma Grande','department' => 'Cordillera','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '402','name' => 'Asunción','department' => 'Capital','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '403','name' => 'Villarrica','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '404','name' => 'Independencia','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '405','name' => 'Paso Yobái','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '406','name' => 'Capitán Mauricio José Troche','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '407','name' => 'Borja','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '408','name' => 'Mbocayaty del Guairá','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '409','name' => 'Iturbe','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '410','name' => 'General Eugenio Alejandrino Garay','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '411','name' => 'Itapé','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '412','name' => 'Coronel Martínez','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '413','name' => 'José A. Fassardi','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '414','name' => 'Félix Pérez Cardozo','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '415','name' => 'Natalicio Talavera','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '416','name' => 'Yataity del Guairá','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '417','name' => 'Ñumí','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '418','name' => 'Tebicuary','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '419','name' => 'San Salvador','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '420','name' => 'Doctor Bottrell','department' => 'Guairá','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '421','name' => 'Encarnación','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '422','name' => 'Cambyretá','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '423','name' => 'San Pedro del Paraná','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '424','name' => 'Tomás Romero Pereira','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '425','name' => 'Edelira','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '426','name' => 'San Rafael del Paraná','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '427','name' => 'Coronel José Félix Bogado','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '428','name' => 'Natalio','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '429','name' => 'Carlos Antonio López','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '430','name' => 'Alto Verá','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '431','name' => 'Obligado','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '432','name' => 'Itapúa Poty','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '433','name' => 'Hohenau','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '434','name' => 'Mayor Otaño','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '435','name' => 'Bella Vista','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '436','name' => 'Capitán Meza','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '437','name' => 'Capitán Miranda','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '438','name' => 'Yatytay','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '439','name' => 'General Artigas','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '440','name' => 'Fram','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '441','name' => 'San Cosme y Damián','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '442','name' => 'Trinidad','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '443','name' => 'San Juan del Paraná','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '444','name' => 'Pirapó','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '445','name' => 'Carmen del Paraná','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '446','name' => 'General Delgado','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '447','name' => 'Nueva Alborada','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '448','name' => 'Jesús','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '449','name' => 'José Leandro Oviedo','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '450','name' => 'La Paz','department' => 'Itapúa','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '451','name' => 'San Ignacio Guazú','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '452','name' => 'San Juan Bautista','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '453','name' => 'Ayolas','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '454','name' => 'Santa Rosa de Lima','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '455','name' => 'Santa María de Fe','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '456','name' => 'Santiago','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '457','name' => 'San Miguel','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '458','name' => 'Villa Florida','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '459','name' => 'San Patricio','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '460','name' => 'Yabebyry','department' => 'Misiones','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '461','name' => 'Pilar','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '462','name' => 'Alberdi','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '463','name' => 'San Juan Bautista del Ñeembucú','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '464','name' => 'Cerrito','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '465','name' => 'Mayor José Martínez','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '466','name' => 'General José Eduvigis Díaz','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '467','name' => 'Tacuaras','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '468','name' => 'Villa Oliva','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '469','name' => 'Laureles','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '470','name' => 'Humaitá','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '471','name' => 'Isla Umbú','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '472','name' => 'Villalbín','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '473','name' => 'Guazú Cuá','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '474','name' => 'Paso de Patria','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '475','name' => 'Desmochados','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '476','name' => 'Villa Franca','department' => 'Ñeembucú','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '477','name' => 'Carapeguá','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '478','name' => 'Yaguarón','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '479','name' => 'Ybycuí','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '480','name' => 'Paraguarí','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '481','name' => 'Quiindy','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '482','name' => 'Pirayú','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '483','name' => 'Acahay','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '484','name' => 'Mbuyapey','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '485','name' => 'San Roque González de Santa Cruz','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '486','name' => 'Escobar','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '487','name' => 'Caapucú','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '488','name' => 'Quyquyhó','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '489','name' => 'Ybytymí','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '490','name' => 'General Bernardino Caballero','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '491','name' => 'Sapucai','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '492','name' => 'La Colmena','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '493','name' => 'Tebicuarymí','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '494','name' => 'María Antonia','department' => 'Paraguarí','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '495','name' => 'Villa Hayes','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '496','name' => 'Teniente Primero Manuel Irala Fernández','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '497','name' => 'Benjamín Aceval','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '498','name' => 'Puerto Pinasco','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '499','name' => 'Nanawa','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '500','name' => 'José Falcón','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '501','name' => 'Teniente Esteban Martínez','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '502','name' => 'General José María Bruguez','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '503','name' => 'Nueva Asunción','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '504','name' => 'Campo Aceval','department' => 'Presidente Hayes','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '505','name' => 'San Estanislao','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '506','name' => 'Capiibary','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '507','name' => 'Santa Rosa del Aguaray','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '508','name' => 'San Pedro de Ycuamandiyú','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '509','name' => 'Guayaibí','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '510','name' => 'Choré','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '511','name' => 'Liberación','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '512','name' => 'General Isidoro Resquín','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '513','name' => 'General Elizardo Aquino','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '514','name' => 'Yrybucuá','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '515','name' => 'Tacuatí','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '516','name' => 'Yataity del Norte','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '517','name' => 'Lima','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '518','name' => 'Itacurubí del Rosario','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '519','name' => 'Villa del Rosario','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '520','name' => '25 de Diciembre','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '521','name' => 'Nueva Germania','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '522','name' => 'Unión','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '523','name' => 'Antequera','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '524','name' => 'San Pablo','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '525','name' => 'San Vicente Pancholo','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '526','name' => 'San José del Rosario','department' => 'San Pedro','is_active' => '1','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL)
          );

        DB::table('city')->insert($city);
    }
}
